### ISSUE TITLE
rplnd2.com, rplnd3.com, rplnd4.com, rplnd5.com, and rplnd6.com

### ISSUE THREAD

**Issue by SilkArt** [badmojr/addons_1Hosts#5]
These domains are used by RexPush network to send push notification ads. Some of the landing pages are NSFW. Please add these domains to both kidsaf and 1hosts.

**Comment by badmojr** [comment]
They have been blocked on Pro, and Xtra for a while now.
see: https://blocklist-tools.developerdan.com/entries/search?q=rplnd3.com
