### ISSUE TITLE
Confused by this list?

### ISSUE THREAD

**Issue by travisboss** [badmojr/addons_1Hosts#6]
My assumption is this is as it says a NSFW list but I see it blocking tracking pixels and the like, so far it has blocked:
```
srv.pixel.parsely.com
uk-script.dotmetrics.net
int.dewrain.site
int.viacore.site
hearst.gscontxt.net
```

I do not think any of these urls have anything to do with NSFW?

**Comment by badmojr** [comment]
That's a plus. Ain't it?

**Comment by travisboss** [comment]
No, this list per it's description:
```
Blocks access to sites with adult, pornographic, & risky content.
Should be used as addon/supplement for mini, Lite, Pro, or Xtra.
```

I do not think anyone would agree what it blocks per my original post is "risky content" by any stretch.

**Comment by badmojr** [comment]
I got better stuff to do. Stay confused!
